# Pandas 
* They are built on top of NumPy NdArrays
* http://pandas.pydata.org/pandas-docs/stable/comparison_with_sql.html

## Objectives

* Create `Series` and `DataFrame`s from Python data types. 
* Create `DataFrame`s from on disk data.
* Index and Slice `pandas` objects.
* Aggregate data in `DataFrame`s.
* Join multiple `DataFrame`s.

## What is Pandas?
A Python library providing data structures and data analysis tools. The name comes from "panel data"; think about it as a way to visualize and sift through tables of data, similar to R or (heaven forfend) Excel.


## Benefits

* Efficient storage and processing of data.
* Includes many built in functions for data transformation, aggregations, and plotting.
* Great for exploratory work.

## Not so greats

* Does not scale terribly well to large datasets.

## Documentation:

* http://pandas.pydata.org/pandas-docs/stable/index.html

In [2]:
#By convention import pandas like:
import pandas as pd

#By convention import numpy like:
import numpy as np


#Make sure you have both lines when using matplotlib in Jupyter notebook
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')

#For fake data.
from numpy.random import randn
np.random.seed(123)
# for future replication

In [ ]:
np.random.randn(3,4) # np.random.randn(3,4).round(2)
# generate a 3 x 4 np array. If you set the seed (i.e. np.random.seed(123))
# in the same cell you'll get exactly the same thing. 


# Pandas is built on Numpy
* Numpy is one of the fundamental packages for scientific computing in Python.


## Numpy Arrays
* Or NdArrays (n-dimensional array)
* They are like lists in Python however they allow faster computation
    1. They are stored as one contiguous block of memory, rather than being spread out across multiple locations like a list. 
    2. Each item in a numpy array is of the same data type (i.e. all integers, all floats, etc.), rather than a conglomerate of any number of data types (as a list is). We call this idea homogeneity, as opposed to the possible heterogeneity of Python lists.


Just how much faster are they? Let's take the numbers from 0 to 1 million, and sum those numbers, timing it with both a list and a numpy array.


In [ ]:
numpy_array = np.arange(0, 1e6)
python_list = list(range(int(1e6)))
#le6 is scientific notation. range only takes integers. create a range 
# of 0 to 10^6 and making a list

#sum list;
print("python list")
time = %timeit -r 1 -o sum(python_list) # -r how many times to repeat the timer (default 3)
print (time.all_runs[0]/time.loops )

#numpy built in sum; - Much Faster!
print("\n" + "numpy array")
time = %timeit -r 1 -o np.sum(numpy_array)
print (time.all_runs[0]/time.loops)

#numpy sum functions slower;
print("\n" + "numpy array -- standard library sum")
time = %timeit -r 1 -o sum(numpy_array)
print(time.all_runs[0]/time.loops)

# Numpy NdArrays

* have types
* Each array is of one type

In [3]:
ints = np.array(range(3))
chars = np.array(list('ABC'))
strings = np.array(['A','BC',"DEF"])

print(ints.dtype, chars.dtype, strings.dtype)

int64 <U1 <U3


In [4]:
chars

array(['A', 'B', 'C'], dtype='<U1')

In [5]:
strings

array(['A', 'BC', 'DEF'], dtype='<U3')

In [6]:
ints

array([0, 1, 2])

In [7]:
ints*0.3 #creates a float default 64

array([0. , 0.3, 0.6])

In [8]:
(ints*0.3).dtype

dtype('float64')

# Creating and using NdArrays

In [9]:
my_lst_ndarray = np.array([1, 2, 3, 4, 5])
my_tuple_ndarray = np.array((1, 2, 3, 4, 5), np.int32) 
#can create an array from a list or tuple. np.int32 is not required

In [10]:
print(my_lst_ndarray.dtype)
print(my_tuple_ndarray.dtype)

int64
int32


In [11]:
print(my_lst_ndarray.shape)
print(my_tuple_ndarray.shape) # array of shape 5

(5,)
(5,)


In [13]:
np.array?

# 2D arrays

In [12]:
nd_arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10],[11, 12, 13, 14, 15]])
nd_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

# Access info in the array
* Individual data
* Slices of data

In [14]:
nd_arr[1,1]

7

In [15]:
nd_arr[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [16]:
nd_arr.shape

(3, 5)

In [17]:
nd_arr.sum()

120

In [ ]:
# nd_arr.sum? # inspect.getsourcelines()

In [18]:
nd_arr.sum(axis=1) #sum rows

array([15, 40, 65])

In [19]:
nd_arr.sum(axis=0) #sum columns

array([18, 21, 24, 27, 30])

In [20]:
nd_arr.max()

15

# Broadcasting

In [21]:
a = np.array([10, -10]) 
b = np.array([1, -1])
c = np.array([0.5, 4, 1])

In [22]:
a

array([ 10, -10])

In [23]:
b

array([ 1, -1])

In [24]:
a + b

array([ 11, -11])

In [31]:
c

array([0.5, 4. , 1. ])

In [30]:
a + c

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [33]:
a = np.array([[10], [-10]]) 
b = np.array([[1, 2], [-1, -2]]) 
# 2x1 and 2x2 can be added
print(a)
print('\n')
print(b)
print("\n\n")
print(a + b)

# elements will "duplicate, expand, and fill up" 
# to make the dimensions compatible for element-wise operations

[[ 10]
 [-10]]


[[ 1  2]
 [-1 -2]]



[[ 11  12]
 [-11 -12]]


In [34]:
a.shape

(2, 1)

In [35]:
print(a)
print(a+4)
print(a*3)
# elementwise operation

[[ 10]
 [-10]]
[[14]
 [-6]]
[[ 30]
 [-30]]


In [37]:
a = np.array([[10, 0, -10, 0],[-10, 0, -10, 0]]) 
b = np.array([[2,2],[-1,0]]) 
print (a.shape, b.shape )
print(a)
print('\n')
print(b)
print("\n\n")
print ("")
# print (a + b)


(2, 4) (2, 2)
[[ 10   0 -10   0]
 [-10   0 -10   0]]


[[ 2  2]
 [-1  0]]






ValueError: operands could not be broadcast together with shapes (2,4) (2,2) 

In [ ]:
# it's not clear how it should fill up in this case... so it can't/doesn't

----------------------------------------------------

## Pandas Series
* are (one dimensional) np.ndarray vectors **with an index**
* They are built upon NdArrays

In [38]:
series = pd.Series([5775,373,7,42,np.nan,33]) #you can supply a list
# creates an index
print(series)
print("\n")
print(series.shape)

0    5775.0
1     373.0
2       7.0
3      42.0
4       NaN
5      33.0
dtype: float64


(6,)


In [39]:
world_series = pd.Series(["cubs","royals","giants","sox","giants","cards","giants","...",None])
world_series

0      cubs
1    royals
2    giants
3       sox
4    giants
5     cards
6    giants
7       ...
8      None
dtype: object

## Pandas Series are very powerful when dealing with dates

In [ ]:
# pd.date_range?

In [42]:
#Datetime index
dt_index = pd.date_range('2015-1-1', 
                        '2015-11-1', 
                        freq='m')
dt_series = pd.Series(randn(10), 
                      index = dt_index)
# be sure to match the dimensions!!!
dt_series

2015-01-31    1.004054
2015-02-28    0.386186
2015-03-31    0.737369
2015-04-30    1.490732
2015-05-31   -0.935834
2015-06-30    1.175829
2015-07-31   -1.253881
2015-08-31   -0.637752
2015-09-30    0.907105
2015-10-31   -1.428681
Freq: M, dtype: float64

## Series methods

In [43]:
dt_series.mean()

0.14451284028523964

# Index
Notice how each series has an index (in this case a relatively meaningless default index).

Pandas can make great use of informative indexes. Indexes work similarly to a dictionary key, allowing fast lookups of the data associated with the index.

Indexes can also be exploited for fast group-bys, merges, time-series operations and lots more.

When you're really in the zone with pandas, you'll be thinking a lot about indexes.

In [44]:
indexed_series = pd.Series(randn(5), 
                           index = ['California', 'Alabama', 
                                    'Indiana', 'Montana', 
                                    'Kentucky'])
alt_indexed_series = pd.Series(randn(5),
                               index = ['Washington', 'Alabama', 
                                        'Montana', 'Indiana', 
                                        'New York'])
print(indexed_series)
print('\n')
print(alt_indexed_series)

California   -0.140069
Alabama      -0.861755
Indiana      -0.255619
Montana      -2.798589
Kentucky     -1.771533
dtype: float64


Washington   -0.699877
Alabama       0.927462
Montana      -0.173636
Indiana       0.002846
New York      0.688223
dtype: float64


In [45]:
#Pandas uses the index by default to align series for arithmetic!
indexed_series + alt_indexed_series
# the ones that match merge and add. like sql outer join and summation

Alabama       0.065708
California         NaN
Indiana      -0.252773
Kentucky           NaN
Montana      -2.972225
New York           NaN
Washington         NaN
dtype: float64

# Pandas DataFrames
* are a set of Pandas Series **that share the same index** 


In [46]:
pd.DataFrame(
    [[1, 2, 3], [4, 5, 6]], 
    columns=['a', 'b', 'c'], 
    index=['foo', 'bar'])

a  b  c
foo  1  2  3
bar  4  5  6

In [47]:
df = pd.DataFrame(randn(10, 5), index=dt_index, columns=[x for x in 'abcde'])
df

a         b         c         d         e
2015-01-31 -0.879536  0.283627 -0.805367 -1.727669 -0.390900
2015-02-28  0.573806  0.338589 -0.011830  2.392365  0.412912
2015-03-31  0.978736  2.238143 -1.294085 -1.038788  1.743712
2015-04-30 -0.798063  0.029683  1.069316  0.890706  1.754886
2015-05-31  1.495644  1.069393 -0.772709  0.794863  0.314272
2015-06-30 -1.326265  1.417299  0.807237  0.045490 -0.233092
2015-07-31 -1.198301  0.199524  0.468439 -0.831155  1.162204
2015-08-31 -1.097203 -2.123100  1.039727 -0.403366 -0.126030
2015-09-30 -0.837517 -1.605963  1.255237 -0.688869  1.660952
2015-10-31  0.807308 -0.314758 -1.085902 -0.732462 -1.212523

## To select just one column, use brackets


In [48]:
df['a']

2015-01-31   -0.879536
2015-02-28    0.573806
2015-03-31    0.978736
2015-04-30   -0.798063
2015-05-31    1.495644
2015-06-30   -1.326265
2015-07-31   -1.198301
2015-08-31   -1.097203
2015-09-30   -0.837517
2015-10-31    0.807308
Freq: M, Name: a, dtype: float64

You can also use the "dot notation" for selecting a column

In [49]:
df.a

2015-01-31   -0.879536
2015-02-28    0.573806
2015-03-31    0.978736
2015-04-30   -0.798063
2015-05-31    1.495644
2015-06-30   -1.326265
2015-07-31   -1.198301
2015-08-31   -1.097203
2015-09-30   -0.837517
2015-10-31    0.807308
Freq: M, Name: a, dtype: float64

Note that this will fail if your column has the same name as a dataframe method, so you may wish to avoid this notation.

In [ ]:
#df.

## To select one row, use .loc[]

In [50]:
df.loc['2015-10-31']

a    0.807308
b   -0.314758
c   -1.085902
d   -0.732462
e   -1.212523
Name: 2015-10-31 00:00:00, dtype: float64

## A column of a dataframe is a series:

In [51]:
col = df['d']
type(col)

pandas.core.series.Series

## So is a row

In [52]:
row = df.loc['2015-01-31']
type(row)

pandas.core.series.Series

### The columns all have the same index:

In [53]:
col.index   

DatetimeIndex(['2015-01-31', '2015-02-28', '2015-03-31', '2015-04-30',
               '2015-05-31', '2015-06-30', '2015-07-31', '2015-08-31',
               '2015-09-30', '2015-10-31'],
              dtype='datetime64[ns]', freq='M')

### What's the index for the rows?

In [54]:
row.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [55]:
df.index

DatetimeIndex(['2015-01-31', '2015-02-28', '2015-03-31', '2015-04-30',
               '2015-05-31', '2015-06-30', '2015-07-31', '2015-08-31',
               '2015-09-30', '2015-10-31'],
              dtype='datetime64[ns]', freq='M')

In [56]:
df.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

## Selecting multiple columns

In [57]:
df[['a','b']]

a         b
2015-01-31 -0.879536  0.283627
2015-02-28  0.573806  0.338589
2015-03-31  0.978736  2.238143
2015-04-30 -0.798063  0.029683
2015-05-31  1.495644  1.069393
2015-06-30 -1.326265  1.417299
2015-07-31 -1.198301  0.199524
2015-08-31 -1.097203 -2.123100
2015-09-30 -0.837517 -1.605963
2015-10-31  0.807308 -0.314758

## Column operations
Just like numpy, operations are broadcast to every element of a column

In [58]:
df['a'] + df['b']

2015-01-31   -0.595909
2015-02-28    0.912395
2015-03-31    3.216879
2015-04-30   -0.768380
2015-05-31    2.565037
2015-06-30    0.091034
2015-07-31   -0.998777
2015-08-31   -3.220303
2015-09-30   -2.443479
2015-10-31    0.492550
Freq: M, dtype: float64

## Adding a new column
It's just like setting by key in a dictionary

In [59]:
df['h'] = abs(df['a'])**df['b']

In [60]:
df

a         b         c         d         e         h
2015-01-31 -0.879536  0.283627 -0.805367 -1.727669 -0.390900  0.964248
2015-02-28  0.573806  0.338589 -0.011830  2.392365  0.412912  0.828553
2015-03-31  0.978736  2.238143 -1.294085 -1.038788  1.743712  0.953034
2015-04-30 -0.798063  0.029683  1.069316  0.890706  1.754886  0.993327
2015-05-31  1.495644  1.069393 -0.772709  0.794863  0.314272  1.538013
2015-06-30 -1.326265  1.417299  0.807237  0.045490 -0.233092  1.492121
2015-07-31 -1.198301  0.199524  0.468439 -0.831155  1.162204  1.036754
2015-08-31 -1.097203 -2.123100  1.039727 -0.403366 -0.126030  0.821233
2015-09-30 -0.837517 -1.605963  1.255237 -0.688869  1.660952  1.329443
2015-10-31  0.807308 -0.314758 -1.085902 -0.732462 -1.212523  1.069695

## Advanced selection


### .loc 
select by row label (index), and column label

In [61]:
df.loc['2015-05-31':'2015-08-31', 'c':'e'] #Ranges by label.

c         d         e
2015-05-31 -0.772709  0.794863  0.314272
2015-06-30  0.807237  0.045490 -0.233092
2015-07-31  0.468439 -0.831155  1.162204
2015-08-31  1.039727 -0.403366 -0.126030

In [62]:
df.loc['2015-05-31':'2015-08-31', 'c':'e'] = 2.7

In [63]:
df

a         b         c         d         e         h
2015-01-31 -0.879536  0.283627 -0.805367 -1.727669 -0.390900  0.964248
2015-02-28  0.573806  0.338589 -0.011830  2.392365  0.412912  0.828553
2015-03-31  0.978736  2.238143 -1.294085 -1.038788  1.743712  0.953034
2015-04-30 -0.798063  0.029683  1.069316  0.890706  1.754886  0.993327
2015-05-31  1.495644  1.069393  2.700000  2.700000  2.700000  1.538013
2015-06-30 -1.326265  1.417299  2.700000  2.700000  2.700000  1.492121
2015-07-31 -1.198301  0.199524  2.700000  2.700000  2.700000  1.036754
2015-08-31 -1.097203 -2.123100  2.700000  2.700000  2.700000  0.821233
2015-09-30 -0.837517 -1.605963  1.255237 -0.688869  1.660952  1.329443
2015-10-31  0.807308 -0.314758 -1.085902 -0.732462 -1.212523  1.069695

### .iloc
select by __positional__ index

In [64]:
df.iloc[2:4,2:5] #Ranges by number.

c         d         e
2015-03-31 -1.294085 -1.038788  1.743712
2015-04-30  1.069316  0.890706  1.754886

### .ix (deprecated)
select by either label or position index
(deprecated because it led to too much ambiguity)

In [ ]:
df.ix[2:-3,2:5] # Figures out what you probably want

In [ ]:
df.ix['2015-05-31':'2015-08-31', 'c':'e']

# DO NOT USE .ix 
It is here so you can recognize it and scold others for using it.
  
  
--------------------------------------------------------------------------------------------     
        
      
      
# Multiple Indices

Start with a df with a single date index

In [68]:
dt_index = pd.date_range('2015-1-1', 
                        '2017-7-1', 
                        freq='m')
df = pd.DataFrame(randn(30,5), index=dt_index)

df

0         1         2         3         4
2015-01-31 -0.001875  0.631948 -1.115040 -1.450683 -0.472531
2015-02-28  1.220569 -0.331128  1.502581 -2.788113 -1.587206
2015-03-31 -0.123689  0.888195 -0.069623 -0.095653 -0.121741
2015-04-30 -1.762898  1.158069 -0.682765  1.089533 -0.070523
2015-05-31  1.068160  0.343258 -0.106674  0.226262 -1.472978
2015-06-30  0.006029  1.716040  1.308194 -0.985024  0.505686
2015-07-31  0.247980  0.817188  0.094153 -0.233504  1.330631
2015-08-31  0.216397  1.255464  0.974386 -0.324487 -0.167000
2015-09-30  1.929832  0.191482 -0.758628 -1.200043  0.974132
2015-10-31  0.160294 -0.792092  0.674585  0.159749 -1.660475
2015-11-30  0.588686  1.333191  2.559850  0.034903  0.232650
2015-12-31  1.606597  0.168722  0.275342 -0.630618 -1.394375
2016-01-31  0.912688 -1.273570  1.140656 -0.788166  0.265234
2016-02-29 -0.372272  1.174600  0.300846  1.959095 -1.083678
2016-03-31  0.413863  0.047342  0.279944  1.595921  0.585318
2016-04-30 -1.147525  0.533511 -0.415619 -0.473355  1.045857
2016-05-31 -0.602340 -0.379730  0.032407  0.946186  0.581590
2016-06-30 -0.234415 -0.272176 -1.160130 -0.759835 -0.654381
2016-07-31 -0.149291  1.986763 -0.675469 -0.295829 -2.052398
2016-08-31  0.600571 -1.577449 -0.906590  1.042335 -2.104928
2016-09-30  0.095920  0.800930  1.525444 -0.920093 -0.624025
2016-10-31  1.804436 -0.025060 -0.736264 -0.717486 -0.972556
2016-11-30 -0.439672  1.088220  0.887766 -1.174270  0.214586
2016-12-31 -0.402160  0.782440 -0.156360  0.371525 -0.158605
2017-01-31 -2.187086  0.047002 -1.271747  0.747128 -0.679828
2017-02-28 -0.605013 -0.008903  0.577794 -0.169744  1.642183
2017-03-31  1.648818  1.715469 -0.234319 -1.481958  1.220079
2017-04-30 -0.416345  0.038166  0.628320 -1.604436  1.629121
2017-05-31  0.874962  0.352272  0.890917  0.556953  0.116828
2017-06-30 -0.307774 -0.739142  0.287214  0.361203  1.083199

Let's add new column of states

In [69]:
df['state'] = ['Alabama', 'Alaska' , 'Arizona'] * 10 
#b/c 30 rows to match dimension
df.head()

0         1         2         3         4    state
2015-01-31 -0.001875  0.631948 -1.115040 -1.450683 -0.472531  Alabama
2015-02-28  1.220569 -0.331128  1.502581 -2.788113 -1.587206   Alaska
2015-03-31 -0.123689  0.888195 -0.069623 -0.095653 -0.121741  Arizona
2015-04-30 -1.762898  1.158069 -0.682765  1.089533 -0.070523  Alabama
2015-05-31  1.068160  0.343258 -0.106674  0.226262 -1.472978   Alaska

`reset_index` shifts the index to a column, then gives the rows a boring old positional index

In [70]:
df = df.reset_index() #to reset everything

In [71]:
df

index         0         1         2         3         4    state
0  2015-01-31 -0.001875  0.631948 -1.115040 -1.450683 -0.472531  Alabama
1  2015-02-28  1.220569 -0.331128  1.502581 -2.788113 -1.587206   Alaska
2  2015-03-31 -0.123689  0.888195 -0.069623 -0.095653 -0.121741  Arizona
3  2015-04-30 -1.762898  1.158069 -0.682765  1.089533 -0.070523  Alabama
4  2015-05-31  1.068160  0.343258 -0.106674  0.226262 -1.472978   Alaska
5  2015-06-30  0.006029  1.716040  1.308194 -0.985024  0.505686  Arizona
6  2015-07-31  0.247980  0.817188  0.094153 -0.233504  1.330631  Alabama
7  2015-08-31  0.216397  1.255464  0.974386 -0.324487 -0.167000   Alaska
8  2015-09-30  1.929832  0.191482 -0.758628 -1.200043  0.974132  Arizona
9  2015-10-31  0.160294 -0.792092  0.674585  0.159749 -1.660475  Alabama
10 2015-11-30  0.588686  1.333191  2.559850  0.034903  0.232650   Alaska
11 2015-12-31  1.606597  0.168722  0.275342 -0.630618 -1.394375  Arizona
12 2016-01-31  0.912688 -1.273570  1.140656 -0.788166  0.265234  Alabama
13 2016-02-29 -0.372272  1.174600  0.300846  1.959095 -1.083678   Alaska
14 2016-03-31  0.413863  0.047342  0.279944  1.595921  0.585318  Arizona
15 2016-04-30 -1.147525  0.533511 -0.415619 -0.473355  1.045857  Alabama
16 2016-05-31 -0.602340 -0.379730  0.032407  0.946186  0.581590   Alaska
17 2016-06-30 -0.234415 -0.272176 -1.160130 -0.759835 -0.654381  Arizona
18 2016-07-31 -0.149291  1.986763 -0.675469 -0.295829 -2.052398  Alabama
19 2016-08-31  0.600571 -1.577449 -0.906590  1.042335 -2.104928   Alaska
20 2016-09-30  0.095920  0.800930  1.525444 -0.920093 -0.624025  Arizona
21 2016-10-31  1.804436 -0.025060 -0.736264 -0.717486 -0.972556  Alabama
22 2016-11-30 -0.439672  1.088220  0.887766 -1.174270  0.214586   Alaska
23 2016-12-31 -0.402160  0.782440 -0.156360  0.371525 -0.158605  Arizona
24 2017-01-31 -2.187086  0.047002 -1.271747  0.747128 -0.679828  Alabama
25 2017-02-28 -0.605013 -0.008903  0.577794 -0.169744  1.642183   Alaska
26 2017-03-31  1.648818  1.715469 -0.234319 -1.481958  1.220079  Arizona
27 2017-04-30 -0.416345  0.038166  0.628320 -1.604436  1.629121  Alabama
28 2017-05-31  0.874962  0.352272  0.890917  0.556953  0.116828   Alaska
29 2017-06-30 -0.307774 -0.739142  0.287214  0.361203  1.083199  Arizona

`set_index` sets columns to indices

In [72]:
df = df.set_index(['state', 'index'])#create a two column index!
df.head()

0         1         2         3         4
state   index                                                       
Alabama 2015-01-31 -0.001875  0.631948 -1.115040 -1.450683 -0.472531
Alaska  2015-02-28  1.220569 -0.331128  1.502581 -2.788113 -1.587206
Arizona 2015-03-31 -0.123689  0.888195 -0.069623 -0.095653 -0.121741
Alabama 2015-04-30 -1.762898  1.158069 -0.682765  1.089533 -0.070523
Alaska  2015-05-31  1.068160  0.343258 -0.106674  0.226262 -1.472978

In [117]:
df.loc['2015-01-31'] #Doesn't work because you are using second index

In [73]:
df.loc['Alabama'].head()

0         1         2         3         4
index                                                       
2015-01-31 -0.001875  0.631948 -1.115040 -1.450683 -0.472531
2015-04-30 -1.762898  1.158069 -0.682765  1.089533 -0.070523
2015-07-31  0.247980  0.817188  0.094153 -0.233504  1.330631
2015-10-31  0.160294 -0.792092  0.674585  0.159749 -1.660475
2016-01-31  0.912688 -1.273570  1.140656 -0.788166  0.265234

In [75]:
df.loc[('Alabama', '2015-01-31')] #Can do this.

0   -0.001875
1    0.631948
2   -1.115040
3   -1.450683
4   -0.472531
Name: (Alabama, 2015-01-31 00:00:00), dtype: float64

# Loading data from a file

In [76]:
df = pd.read_csv('data/winequality-red.csv', delimiter=';')

In [77]:
df.head()  #Display the first x rows (default is 5)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [78]:
df.shape

(1599, 12)

In [79]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
fixed acidity           1599 non-null float64
volatile acidity        1599 non-null float64
citric acid             1599 non-null float64
residual sugar          1599 non-null float64
chlorides               1599 non-null float64
free sulfur dioxide     1599 non-null float64
total sulfur dioxide    1599 non-null float64
density                 1599 non-null float64
pH                      1599 non-null float64
sulphates               1599 non-null float64
alcohol                 1599 non-null float64
quality                 1599 non-null int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [81]:
df.describe() #summary stats

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

In [82]:
df.tail()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6

# Filtering (i.e., row selecting or boolean indexing)

In [119]:
df['chlorides']

In [120]:
df['chlorides'] <= 0.08 

In [85]:
mask = df['chlorides'] <= 0.08 

In [121]:
mask

In [87]:
type(mask)

pandas.core.series.Series

You can use a boolean series to "mask" a dataframe / series, returning only those rows where the mask is `True`

In [116]:
df[mask] # will use frequently in EDA

In [118]:
# Okay, this is cool. What if I wanted a slightly more complicated query...
df[(df['chlorides'] >= 0.04) & (df['chlorides'] < 0.08)]

In [90]:
df2 = df[(df['chlorides'] >= 0.04) & (df['chlorides'] < 0.08)][['pH','fixed acidity']]

In [91]:
df2.head()

pH  fixed acidity
0  3.51            7.4
3  3.16           11.2
4  3.51            7.4
5  3.51            7.4
6  3.30            7.9

In [92]:
df2.sort_values('pH').reset_index().head() #re-index so consecutive

index    pH  fixed acidity
0    544  2.86           14.3
1    440  2.88           12.6
2   1017  2.89            8.0
3   1018  2.89            8.0
4    657  2.92           12.0

In [93]:
df2.sort_values('pH').reset_index(drop=True).head() #dropped the index column

pH  fixed acidity
0  2.86           14.3
1  2.88           12.6
2  2.89            8.0
3  2.89            8.0
4  2.92           12.0

# Groupby

In [94]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [95]:
g = df.groupby('quality') # Note that this returns back to us a groupby object. It doesn't actually 
                      # return to us anything useful until we perform some aggregation on it. 
g

In [96]:
g.max()['density']

quality
3    1.00080
4    1.00100
5    1.00315
6    1.00369
7    1.00320
8    0.99880
Name: density, dtype: float64

In [97]:
# Note we can also group by multilple columns by passing them in in a list. It will group by 
# the first column passed in first, and then the second after that (i.e. it will group by 
# the second within the group by of the first). 
df2 = df.groupby(['pH', 'quality']).count()['chlorides']

df2

pH    quality
2.74  4          1
2.86  6          1
2.87  6          1
2.88  5          1
      8          1
2.89  5          2
      6          2
2.90  6          1
2.92  5          3
      7          1
2.93  5          1
      6          2
2.94  5          2
      6          2
2.95  7          1
2.98  5          2
      6          1
      7          1
      8          1
2.99  5          2
3.00  5          4
      6          2
3.01  5          1
      6          1
      7          3
3.02  5          3
      6          1
      7          4
3.03  5          4
      6          2
                ..
3.61  5          3
      6          5
3.62  4          1
      5          2
      6          1
3.63  3          1
      5          2
3.66  4          1
      5          2
      6          1
3.67  5          2
      6          1
3.68  5          2
      6          2
      7          1
3.69  5          2
      6          2
3.70  6          1
3.71  6          1
      7          3
3.72  5          

# Remove columns

In [ ]:
# add a computed column

df['pct_free_sulf'] = df['free sulfur dioxide'] / df['total sulfur dioxide']

In [ ]:
df.head()

In [ ]:
# Dropping a row

In [ ]:
# df.drop('pct_free_sulf') #need an axis is col, default is row

In [ ]:
df.drop('pct_free_sulf', axis = 1) #axis is a column

In [ ]:
df.columns

# Managing Missing Values
* http://pandas.pydata.org/pandas-docs/stable/missing_data.html

In [98]:
miss_val_df = pd.DataFrame(
    [[1, 2, 3], [4, np.nan, 6]], 
    columns=['a', 'b', 'c'], 
    index=['foo', 'bar'])
miss_val_df

a    b  c
foo  1  2.0  3
bar  4  NaN  6

In [99]:
miss_val_df.fillna(0) #impute missing data. can use avg, median, max, min, 0

a    b  c
foo  1  2.0  3
bar  4  0.0  6

In [100]:
miss_val_df #df didn't change itself with fillna

a    b  c
foo  1  2.0  3
bar  4  NaN  6

In [101]:
# IF YOU WANT THE CHANGE TO HAPPEN INPLACE YOU MUST SPECIFY:
miss_val_df.fillna(0,inplace=True)
miss_val_df

a    b  c
foo  1  2.0  3
bar  4  0.0  6

In [ ]:
## DROP ROW

In [ ]:
miss_val_df['b']['foo'] =np.nan

In [ ]:
miss_val_df

In [ ]:
miss_val_df.dropna() #drop rows that contain na

# Merge 
* http://pandas.pydata.org/pandas-docs/stable/merging.html

We can join DataFrames in a similar way that we join tables to SQL.  In fact, left, right, outer, and inner joins work the same way here.

In [102]:
merge1 = pd.DataFrame(
    [[1, 2, 3], [4, 3, 6]], 
    columns=['a', 'b', 'c'])

merge2 = pd.DataFrame(
    [[1, 2, 3], [4, 3, 6]], 
    columns=['z', 'b', 'y'])

print(merge1); print(""); print(merge2)

   a  b  c
0  1  2  3
1  4  3  6

   z  b  y
0  1  2  3
1  4  3  6


In [103]:
merged_df = merge1.merge(merge2, how='outer')

In [104]:
merged_df

a  b  c  z  y
0  1  2  3  1  3
1  4  3  6  4  6

# Concatenating
* adding *rows*
* see also: df.append()

In [105]:
df1 = pd.DataFrame(
    {'Col1': range(5), 'Col2': range(5), 'Col3': range(5)})
df2 = pd.DataFrame(
    {'Col1': range(5), 'Col2': range(5), 'Col4': range(5)},
    index=range(5, 10))

In [106]:
df1

Col1  Col2  Col3
0     0     0     0
1     1     1     1
2     2     2     2
3     3     3     3
4     4     4     4

In [107]:
df2

Col1  Col2  Col4
5     0     0     0
6     1     1     1
7     2     2     2
8     3     3     3
9     4     4     4

In [108]:
#Vertically
pd.concat([df1, df2], axis=0)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


Col1  Col2  Col3  Col4
0     0     0   0.0   NaN
1     1     1   1.0   NaN
2     2     2   2.0   NaN
3     3     3   3.0   NaN
4     4     4   4.0   NaN
5     0     0   NaN   0.0
6     1     1   NaN   1.0
7     2     2   NaN   2.0
8     3     3   NaN   3.0
9     4     4   NaN   4.0

In [109]:
pd.concat([df1, df2], join='outer', axis=1)

Col1  Col2  Col3  Col1  Col2  Col4
0   0.0   0.0   0.0   NaN   NaN   NaN
1   1.0   1.0   1.0   NaN   NaN   NaN
2   2.0   2.0   2.0   NaN   NaN   NaN
3   3.0   3.0   3.0   NaN   NaN   NaN
4   4.0   4.0   4.0   NaN   NaN   NaN
5   NaN   NaN   NaN   0.0   0.0   0.0
6   NaN   NaN   NaN   1.0   1.0   1.0
7   NaN   NaN   NaN   2.0   2.0   2.0
8   NaN   NaN   NaN   3.0   3.0   3.0
9   NaN   NaN   NaN   4.0   4.0   4.0

# Categorical data

In [110]:
df = pd.read_csv('data/playgolf.csv', delimiter=',' )
df.head()

Date   Outlook  Temperature  Humidity  Windy      Result
0  7/1/14     sunny           85        85  False  Don't Play
1  7/2/14     sunny           80        90   True  Don't Play
2  7/3/14  overcast           83        78  False        Play
3  7/4/14      rain           70        96  False        Play
4  7/5/14      rain           68        80  False        Play

df.value_counts() gets you the frequencies

In [111]:
df['Outlook'].value_counts()

rain        5
sunny       5
overcast    4
Name: Outlook, dtype: int64

Using apply will get you the value counts for multiple columns at once

In [112]:
df[['Outlook','Result']].apply(lambda x: x.value_counts())

Outlook  Result
Don't Play      NaN     5.0
Play            NaN     9.0
overcast        4.0     NaN
rain            5.0     NaN
sunny           5.0     NaN

Contingency Tables for looking at bivariate relationships between two categorical variables

In [113]:
pd.crosstab(df['Outlook'], df['Result'])

Result    Don't Play  Play
Outlook                   
overcast           0     4
rain               2     3
sunny              3     2

Often we want the row percentages

In [114]:
pd.crosstab(df['Outlook'], df['Result']).apply(lambda r: r/r.sum(), axis=1)

Result    Don't Play  Play
Outlook                   
overcast         0.0   1.0
rain             0.4   0.6
sunny            0.6   0.4

Or the column percentages

In [115]:
pd.crosstab(df['Outlook'], df['Result']).apply(lambda c: c/c.sum(), axis=0)

Result    Don't Play      Play
Outlook                       
overcast         0.0  0.444444
rain             0.4  0.333333
sunny            0.6  0.222222

# Plotting DataFrames

In [ ]:
df = pd.read_csv('data/playgolf.csv', delimiter=',' )
df.head()

In [ ]:
df.hist(['Temperature','Humidity'],bins=5);

In [ ]:
df[['Temperature','Humidity']].plot(kind='box');

In [ ]:
df.plot('Temperature', 'Humidity', kind='scatter');

In [ ]:
groups=df.groupby('Outlook')
for name, group in groups:
    print(name)

In [ ]:
fig, ax = plt.subplots()

ax.margins(0.05)
for name, group in groups:
    ax.plot(group.Temperature, group.Humidity,\
            marker='o', linestyle='', ms=12, label=name)
ax.legend(numpoints=1, loc='lower right')

plt.show()

In [ ]:
df.head()

In [ ]:
df['Outlook'].value_counts()

In [ ]:
df['Windy'].value_counts()

In [ ]:
g = df.groupby(['Outlook', 'Windy'])

In [ ]:
g.max

In [ ]:
g.agg(max)

In [ ]:
df_th = g.agg(max)[['Temperature','Humidity']]
df_th

In [ ]:
df_th.unstack()

In [ ]:
df_th.unstack()['Temperature']

In [ ]:
df_th.reset_index()

In [ ]:
df

In [ ]:
df.pivot(columns='Outlook')

In [ ]:
df.pivot?